name: "WarpBuild Unprivileged userns"
description: "Intended for WaprBuild runners: Enables unprivilged userns (AppArmor)"
inputs: {}

runs:
  using: "composite"
  steps:
    - name: Allow unprivileged userns (workaround)
      if: ${{ startsWith(runner.name, 'warp-') }}
      run: |
        sudo apt-get install apparmor-profiles
        sudo ln -s /etc/apparmor.d/unprivileged_userns /etc/apparmor.d/disable/
        sudo apparmor_parser -r /etc/apparmor.d/unprivileged_userns
      shell: bash
