name: "WarpBuild Unprivileged userns"
description: "Intended for WaprBuild runners: Enables unprivilged userns (AppArmor)"
inputs: {}

runs:
  using: "composite"
  steps:
    - name: Allow unprivileged userns (workaround)
      if: ${{ startsWith(runner.name, 'warp-') }}
      run: |
        sudo apt-get update
        sudo apt-get install apparmor-profiles
        sudo tee /etc/apparmor.d/unprivileged_userns > /dev/null <<'EOF'
        #include <tunables/global>
        profile unprivileged_userns flags=(attach_disconnected,mediate_deleted) {
          #include <abstractions/base>
          capability,
          mount,
          umount,
          file,
          network,
          signal,
          ptrace,
          unix,
          pivot_root,
        }
        EOF
        sudo apparmor_parser -r /etc/apparmor.d/unprivileged_userns
      shell: bash
